sudo: required
language: node_js

addons:
  chrome: stable

node_js:
  - "8.9.1"

cache:
  directories:
    - $HOME/.meteor
    - $HOME/.npm

before_cache:
  - rm -f $HOME/.meteor/log/*.log

before_install:
  # Download Meteor - Keep in mind that you need
  # to remove your travis cache to get meteor updates
  - export PATH="$HOME/.meteor:$PATH"
  - curl https://install.meteor.com/?release=1.8 | /bin/sh

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - cd bare-exemple/ && meteor npm install
  - npm install -g eslint coveralls codecov.io codacy-coverage

script:
  - meteor npm run test:coverage
  - sed .coverage/lcov.info | coveralls || true # ignore coveralls error
  - sed -i 's/^SF:/SF:bare-exemple\//g' .coverage/lcov.info
  - cat .coverage/lcov.info | codecov || true # ignore codecov error
  - cat .coverage/lcov.info | codacy-coverage || true # ignore codacy error