version: 2
jobs:
  build:
    docker:
      - image: circleci/node:latest-browsers
    working_directory: ~/meteor-coverage
    steps:
      - checkout
      - run: curl https://install.meteor.com | /bin/sh
      - run: cd bare-exemple
      - run: meteor npm install
      - run: meteor npm run test:coverage
      - run: meteor npm run lint || true # ignore eslint error
